
version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: not2do_api
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - not2do_network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: not2do_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - not2do_network
    restart: unless-stopped

networks:
  not2do_network:
    driver: bridge

volumes:
  .:
  mongodb_data:
